const arrows = [
  {
    direction: "right",
    initialCoordinate: [14.316, -88.0],
    finalCoordinate: [14.0, -87.6],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Yojoa to Centro",
    positive: "right",
    negative: "left",
    flowId: 1,
  },
  {
    direction: "right",
    initialCoordinate: [15.1, -89.6],
    finalCoordinate: [15.1, -89.2],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Guatemala to La Entrada",
    positive: "left",
    negative: "right",
    flowId: 2,
  },
  {
    direction: "right",
    initialCoordinate: [15.263, -88.7],
    finalCoordinate: [15.263, -88.3],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from La Entrada to El Cajon",
    positive: "left",
    negative: "right",
    flowId: 3,
  },
  {
    direction: "left",
    initialCoordinate: [15.07, -88.1],
    finalCoordinate: [15.07, -87.85],
    size: 10.5,
    speed: 3000,
    count: 5,
    description: "Arrow from Yojoa to El Progreso",
    positive: "right",
    negative: "left",
    flowId: 4,
  },
  {
    direction: "right",
    initialCoordinate: [15.606, -86.7],
    finalCoordinate: [15.606, -86.2],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Litoral to El Progreso",
    positive: "right",
    negative: "left",
    flowId: 5,
  },
  {
    direction: "right",
    initialCoordinate: [14.76, -86.7],
    finalCoordinate: [14.76, -86.2],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Centro to Olancho",
    positive: "right",
    negative: "left",
    flowId: 6,
  },
  {
    direction: "right",
    initialCoordinate: [14.307, -86.7],
    finalCoordinate: [14.307, -86.2],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Centro to El Paraiso",
    positive: "right",
    negative: "left",
    flowId: 7,
  },
  {
    direction: "right",
    initialCoordinate: [13.68, -88.2],
    finalCoordinate: [13.68, -87.6],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from El Salvador to Honduras",
    positive: "left",
    negative: "right",
    flowId: 8
  },
  // VERTICAL ARROWS
  {
    direction: "up",
    initialCoordinate: [14.85, -87.398],
    finalCoordinate: [14.38, -87.398],
    size: 10.5,
    speed: 3000,
    count: 7,
    description: "Arrow from Centro to El Cajon",
    positive: "down",
    negative: "up",
    flowId: 9
  },
  {
    direction: "up",
    initialCoordinate: [14.85, -88.4717],
    finalCoordinate: [14.5, -88.4717],
    size: 10.5,
    speed: 3000,
    count: 6,
    description: "Arrow from Occidente to Yojoa",
    positive: "down",
    negative: "up",
    flowId: 10
  },
  {
    direction: "up",
    initialCoordinate: [15.58, -88.16],
    finalCoordinate: [15.35, -88.16],
    size: 10.5,
    speed: 3000,
    count: 4,
    description: "Arrow from Yojoa to Cortes",
    positive: "down",
    negative: "up",
    flowId: 11
  },
  {
    direction: "up",
    initialCoordinate: [15.61, -87.3922],
    finalCoordinate: [15.28, -87.3922],
    size: 10.5,
    speed: 3000,
    count: 5,
    description: "Arrow from El Progreso to Cortes",
    positive: "up",
    negative: "down",
    flowId: 12
  },
  {
    direction: "up",
    initialCoordinate: [13.4, -86.7],
    finalCoordinate: [12.7, -87],
    size: 10.5,
    speed: 3000,
    count: 8,
    description: "Arrow from Nicaragua to Honduras",
    positive: "down",
    negative: "up",
    flowId: 13
  },
  {
    direction: "up",
    initialCoordinate: [14.2, -87.2],
    finalCoordinate: [13.6, -87.2],
    size: 10.5,
    speed: 3000,
    count: 8,
    description: "Arrow from Sur to Centro",
    positive: "up",
    negative: "down",
    flowId: 14
  },
  {
    direction: "up",
    initialCoordinate: [15.19, -87.397],
    finalCoordinate: [14.96, -87.397],
    size: 10.5,
    speed: 3000,
    count: 4,
    description: "Arrow from El Cajon to El Progreso",
    positive: "up",
    negative: "down",
    flowId: 15
  },
];

export default arrows;