// generationAreas.js
export const generationBoxContainerArray = [
  {
    topLeftPosition: [16.15, -88.5],
    bottomRightPosition: [15.5, -88.2],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Cortes",
    idZona: 1,
  },
  {
    topLeftPosition: [13.65, -87.67],
    bottomRightPosition: [12.7, -87.4],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Sur",
    idZona: 2,
  },
  {
    topLeftPosition: [14.73, -87.05],
    bottomRightPosition: [14.33, -86.85],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Centro",
    idZona: 3,
  },
  {
    topLeftPosition: [14.3, -88.89],
    bottomRightPosition: [13.7, -88.7],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Occidente",
    idZona: 4,
  },
  {
    topLeftPosition: [14.95, -87.3],
    bottomRightPosition: [14.7, -87.08],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area El Cajon",
    idZona: 5,
  },
  {
    topLeftPosition: [14.84, -88.15],
    bottomRightPosition: [14.3, -87.95],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Yojoa",
    idZona: 6,
  },
  {
    topLeftPosition: [15.95, -85.25],
    bottomRightPosition: [15, -84.9],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Litoral",
    idZona: 7,
  },
  {
    topLeftPosition: [15, -85.25],
    bottomRightPosition: [14.3, -85.05],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area Olancho",
    idZona: 8,
  },
  {
    topLeftPosition: [14.3, -85.7],
    bottomRightPosition: [13.6, -85.5],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area El Paraiso",
    idZona: 9,
  },
  {
    topLeftPosition: [15.35, -86.82],
    bottomRightPosition: [14.8, -86.63],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area El Progreso",
    idZona: 10,
  },
  {
    topLeftPosition: [15.02, -89.25],
    bottomRightPosition: [14.5, -88.9],
    color: "transparent",
    hoverColor: "#f4f4f4",
    description: "Generation Area La Entrada",
    idZona: 13,
  },
];

export default generationBoxContainerArray;
